apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: y6fun18tf-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-ab166d8dd4.c7kx.p3.openshiftapps.com/rhtap/rhtap-qe:85550ca76918c3eab5849edc318c361ed4e5ccb0@sha256:c3f47d3682f9485fbbe3bdc34e3e7330140a806e0700272615a5bdde172d1443
          name: container-image
